modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="betterskills"
version="1.4.0"
displayName="Better Skills"
credits="Made by FeuSalamander"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-skills"
logoFile="logo.png"
authors="FeuSalamander"
description='''
add skills to your game
'''

[[dependencies.betterskills]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.betterskills]]
    modId="just_enough_items-1.16.5"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterskills]]
    modId="patchouli-1.16.5"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

