modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="betterskills"
version="1.5.0"
displayName="Better Skills"
credits="Made by FeuSalamander"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-skills"
logoFile="logo.png"
authors="FeuSalamander"
description='''
add skills to your game
'''

[[dependencies.betterskills]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.betterskills]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

